final products= [
  {
    "id":1,
    "title": "men's Nike shoes",
    "price": 999,
    "imageUrl":"assets/images/shoes_1.png",
    "company":"Nike",
    "sizes": [8,9,10,11],
  },
  {
    "id":2,
    "title": "Adidas shoes",
    "price": 699,
    "imageUrl":"assets/images/shoes_2.png",
    "company":"Adidas",
    "sizes": [8,9,10,11],
  },
  {
    "id":3,
    "title": "Jordan shoes",
    "price": 899,
    "imageUrl":"assets/images/shoes_5.png",
    "company":"Jordan",
    "sizes": [8,9,10,11],
  },
  {
    "id":4,
    "title": "Cr7 shoes",
    "price": 749,
    "imageUrl":"assets/images/shoes_7.png",
    "company":"Cr7",
    "sizes": [8,9,10,11],
  },
  {
    "id":5,
    "title": "Puma shoes",
    "price": 1999,
    "imageUrl":"assets/images/shoes_6.png",
    "company":"Puma",
    "sizes": [8,9,10,11],
  },
  {
    "id":6,
    "title": "Reebok shoes",
    "price": 1499,
    "imageUrl":"assets/images/shoes_3.png",
    "company":"Reebok",
    "sizes": [8,9,10,11],
  },
  {
    "id":7,
    "title": "Adidas shoes",
    "price": 850,
    "imageUrl":"assets/images/shoes_1.png",
    "company":"Adidas",
    "sizes": [8,9,10],
  },

];
